version: '3.8'

services:
  database:
    container_name: database
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
